### ISSUE TITLE
new website/service

### ISSUE THREAD

**Issue by tipoul** [amirshnll/rtbf.ir#101]
"name" : "شبکه پرداخت تیپول"
"website": "https://about.tipoul.com"
"deleteurl": "https://panel.tipoul.com/notification/tickets"
"info": "حذف حساب کاربری با ایجاد تیکتی با همین عنوان از بخش تیکت ها در پنل کاربری انجام می شود."

**Comment by Matin-B** [comment]
مرسی بابت مشارکت.
