### ISSUE TITLE
new website/service

### ISSUE THREAD

**Issue by AliKarbasiCom** [amirshnll/rtbf.ir#102]
"name" : "سولوکُد"
"website": "https://solocode.ir"
"deleteurl": "https://solocode.ir/delete"
"info": "درخواست حذف حساب کاربری را به ایمیل پشتیبانی سولوکُد ارسال کنید. قبل از ثبت درخواست، نکاتی که در صفحه [حذف حساب کاربری](https://solocode.ir/delete) نوشته شده را مطالعه کنید."

**Comment by Matin-B** [comment]
وب‌سایت اضافه شد.
سپاس بابت مشارکت 🙏
