### ISSUE TITLE
new blog post

### ISSUE THREAD

**Issue by darafshi** [amirshnll/rtbf.ir#103]
عنوان : "یادم تو را فراموش"
متن : "پس از آشنایی با حق فراموشی که چند سال پیش اتفاق افتاد، اولین فکری که به ذهنم خطور کرد این بود که چرا باید چنین حقی وجود داشته باشد؟ مگر می شود بتوانم بگویم که من حق دارم فراموش شوم؟ اگر من از سرویسی استفاده کنم؛ مگر مالک آن داده ای که به آن می دهم نیست؟
در یک کلام باید بگویم که شما مالک و صاحب دیتایی هستید که ایجاد می کنید و می توانید در هر لحظه بخواهید که آن اطلاعات از بین برود. اگر چنین حقی وجود نداشته باشد بنابراین سرویسی که استفاده می کنید از دیتای شما سوء استفاده می کند. سوء استفاده نه به این معنی که با آن اطلاعات بخواهد کار بدی انجام دهد یا آنها را بفروشد. نه .بلکه به این معنی که حضور شما به عنوان مقادیری اطلاعات در یک سرویس می تواند در تصمیم گیری های کلان و امور داده کاوی نقشی هر چند کوچک ایفا کند. انسان موجود عجیبی است. شاید من نخواهم همان تغییر و تاثیر کوچک را مسبب شوم.
شما مالک آنچه که ایجاد می کنید هستید. خواه می خواهد یک وبسایت عظیم یا دیتایی باید که به صورت ناشناس با یک سرویس اینترنتی به اشتراک می گذارید. گاهی به این موضوع فکر می کنم که دیتایی که من با سرویس های آنلاین به اشترک می گذارم دو قسمت است. قسمت اول که آشکار و خودخواسته است. مثلا عکسی را آپلود می کنم یا تاریخ تولدم را ثبت می کنم. اینها آشکار هستند و من می باید این اختیار را داشته باشم که هر موقع دلم خواست این اطلاعات را ویرایش یا حذف کنم. اما صورت دیگری از اطلاعات من و شما هستند که به صورت ناشناس در صورت استفاده از یک سرویس یا اپلیکیشن جمع آوری می شوند. از این اطلاعات عموما برای ایجاد یک تجربه ی جدید کاربری در یک اپ یا جمع آوری آماری برای تصمیم های آتی در یک سرویس استفاده می شود. اگر من مایل به استفاده از حق فراموشی باشم آیا چنین دیتایی نیز می باید پاک شود یا این دیتای ناشناس گردآوری شده همچنان در چرخه می ماند؟ 
منظور از دیتای ناشناس اطلاعاتی است که ارتباط مستقیم با هویت من ندارد اما به کمک یک شناسه یا یک دیوایس آیدی به دستگاه یا شناسه کاربری که من استفاده کرده ام مربوط می شوند
گاهی به این می اندیشم که ما غول های اطلاعاتی را ساختیم. حالا خودمان از آنها می ترسیم.

مهدی د."

**Comment by amirshnll** [comment]
@darafshi 

متشکرم از نوشته ی شما
<br />
اگر نوشته به صورت دست نوشته  نیست و ترجمه یا برگرفته از جایی هست لطفا لینک منبع رو هم اعلام کنید متشکرم

**Comment by darafshi** [comment]
@amirshnll 
سلام. این نوشته از دست نوشته های خودم است

با احترام

**Comment by Mohammadpro** [comment]
عالی بود من خودم تازه اومدم توی ریپو
کارتون عالیه 👋

**Comment by amirshnll** [comment]
https://rtbf.ir/post/I-forget-you-note
