### ISSUE TITLE
new website/service

### ISSUE THREAD

**Issue by aliHOZA** [amirshnll/rtbf.ir#106]
"name" : "وان دی آف"
"website": "https://www.1dayoff.com/"
"deleteurl": "https://www.1dayoff.com/"
"info": "این سایت اقدام بخ ارسال پیامک‌های روزانه میکند و امکان لغو آن را به کاربر نمی‌دهد. "

**Comment by Matin-B** [comment]
درود
سپاس بابت مشارکت. پس از بررسی اضافه خواهد شد.
