### ISSUE TITLE
new website/service

### ISSUE THREAD

**Issue by AmirhBeigi** [amirshnll/rtbf.ir#108]
"name" : "پذیرش24"
"website": "https://www.paziresh24.com"
"deleteurl": ""
"info": "غیرممکن"

**Comment by Matin-B** [comment]
درود
با توجه به بخش بروزرسانی یا حذف اطلاعات موجود در صفحه [سیاست حفظ حریم خصوصی](https://www.paziresh24.com/home/privacy-policy/) وب‌سایت مورد نظر  پس از بررسی چگونگی حذف حساب کاربری اطلاعات سرویس اضافه خواهد شد.

سپاس بابت مشارکت

**Comment by Matin-B** [comment]
جهت حذف حساب کاربری درخواست خود را از طریق [صفحه پشتیبانی](https://www.paziresh24.com/home/support-form-other) ثبت کنید.
