### ISSUE TITLE
new website/service

### ISSUE THREAD

**Issue by neticall** [amirshnll/rtbf.ir#111]
"name" : "فایل سل"
"website": "https://filesell.ir/"
"deleteurl": ""
"info": "در صورت درخواست حذف حساب ، حساب رو مسدود میکنن و وقتی میزنیم فراموشی رمز عبور متوجه میشیم که ایمیل ما داخل دیتابیس سایت هنوز وجود داره و فقط امکان لاگین رو نداریم"

**Comment by Matin-B** [comment]
درود
مرسی بابت مشارکت
ایمیل برای پشتیبانی ارسال شد. پس از بررسی اضافه خواهد شد.

**Comment by amirshnll** [comment]
@Matin-B 

متین جان اگر پشتیبانی پاسخ درستی بهت داد و پاسخگویی مناسبی داشتن برای پادکست هم بهشون پیشنهاد بده

**Comment by Matin-B** [comment]
> @Matin-B
> 
> متین جان اگر پشتیبانی پاسخ درستی بهت داد و پاسخگویی مناسبی داشتن برای پادکست هم بهشون پیشنهاد بده

حتما. فعلا که جوابی دریافت نکردم اما از این به بعد اگر پشتیبانی خوبی داشتند بهشون پیشنهاد می‌کنم.
