### ISSUE TITLE
new website/service

### ISSUE THREAD

**Issue by neticall** [amirshnll/rtbf.ir#115]
"name" : "نفیس فایل"
"website": "http://nafisfile.com/"
"deleteurl": ""
"info": "باید درخواست حذف حساب کاربریتون رو به ایمیل info@nafisfile.com ارسال کنید و پس از چند ساعت حساب کاربریتون حذف خواهد شد."

**Comment by Matin-B** [comment]
درود
اضافه شد.

مرسی بابت مشارکت
