### ISSUE TITLE
Arvancloud website/service

### ISSUE THREAD

**Issue by voxxp** [amirshnll/rtbf.ir#125]
"name" : "ابر آروان"
"website": "https://www.arvancloud.com/"
"deleteurl": "ندارد"
"info": "شرایط استفاده از خدمات: در حال حاضر امکان حذف یا غیرفعال کردن حساب کاربری وجود ندارد."

**Comment by Matin-B** [comment]
درود
سرویس معرفی شده قبلا ثبت شده است.
