### ISSUE TITLE
پلاگین کروم

### ISSUE THREAD

**Issue by dashtaki** [amirshnll/rtbf.ir#128]
عنوان : "پلاگین کروم"
متن : "زمان ورود به وب سایت که قبلا rtbf ذخیره شده بود کاربربتواند وضعیت وب‌سایت را مشاهده کند. برای مثال اگر وب‌سایت قابلیت حذف حساب کاربری داشت که قبلا در سایت ذکر کردیم در پلاگین قابل مشاهده باشه"

**قابلیت های دیگر :**
-  دکمه  "درخواست بررسی" برای حالتی که اطلاعاتی از وب‌سایت مورد نظر موجود نیست
-  دکمه  "تصحیح " برای ویرایش اطلاعات موجود
- تغییر رنگ ایکن بالای مرورگر با توجه به نوع حذف شدن

**Comment by amirshnll** [comment]
#112 


فیدبک شما به بخش roadmap اضافه میشه این issue بسته بشه
متشکرم
