### ISSUE TITLE
دلیل نداشتن امکان حذف اکانت در پی پینگ

### ISSUE THREAD

**Issue by ashkanRmk** [amirshnll/rtbf.ir#2]
سلام
مرسی از دغدغه درستی که پیگیرش هستین
اما باید بگم که در پرداختیار پی پینگ چون عملن ما زیرمجموعه بانک مرکزی و شاپرک هستیم و ملزم به رعایت قوانین اونا هم هستیم.
طبق قوانین شاپرک و همینطور پلیس فتا ما باید در هر لحظه بتونیم ریزتراکنش های هر کاربری که از طریق ترمینال های ثبتی از طرف پرداختیاری پی‌پینگ ثبت شده رو در اختیار اونا قرار بدیم.
حتا اگر اون شخص سالهاست فعالیت نمیکنه.
برای همین ما به دلیل قانونی امکان حذف هیچگونه از لاگ‌های فعالیت کاربر اعم از تراکنش یا حساب کاربری رو نداریم.
در نهایت ما امکان سافت دیلیت رو داریم و اگر از طریق پشتیبانی اعلام کنین، اکانت شما به صورت کامل غیرفعال میشه. اما بازم به صورت آرشیو شده در بایگانی دیتاهای ما برای ارجاعات احتمالی قانونی بعدی وجود داره.
مرسی از توجهتون ✌️

**Comment by amirshnll** [comment]
@ashkanRmk 

مرسی از توضیحات خوب و کامل شما

**Comment by ashkanRmk** [comment]
ممنون میشم علت این داستان رو داخل سایت هم ذکر کنین.

برای دونیت پروژه های گیتهاب هم اگر دوست داشتین میتونین به این شکل از قابلیت گیتهاب اسپانسر استفاده کنین برای پرداخت ریالی:
https://ashkanam.ir/blog/github-sponsor/

**Comment by amirshnll** [comment]
> ممنون میشم علت این داستان رو داخل سایت هم ذکر کنین.
> 
> برای دونیت پروژه های گیتهاب هم اگر دوست داشتین میتونین به این شکل از قابلیت گیتهاب اسپانسر استفاده کنین برای پرداخت ریالی:
> https://ashkanam.ir/blog/github-sponsor/

اضافه شد <br />
در مورد دونیت هم فعلا نیاز به حمایت ریالی برای این پروژه نیست وگرنه روی ریپوزیتوری های دیگر درگاه های ریالی استفاده کردم.
<br />
باز هم از پاسخگوییت ممنونم موفق باشید
