### ISSUE TITLE
new website/service

### ISSUE THREAD

**Issue by IVIosi** [amirshnll/rtbf.ir#20]
"name" : "جاب ویژن"
"website": "https://jobvision.ir/"
"deleteurl": ""
"info": "غیرممکن"

**Comment by Matin-B** [comment]
در قسمت [پرسش های متداول](https://jobvision.ir/faq) وبسایت و در سوال شماره 5 به وضوح این مورد توضیح داده شده:

"برای غیرفعال‌سازی موقت حساب کاربری، وارد حساب کاربری خود شوید و در بخش تنظیمات، گزینه غیرفعال‌سازی موقت حساب کاربری را انتخاب نمایید. برای درخواست حذف حساب کاربری، لازم است از طریق ایمیل ثبت نام شده بر روی سایت، درخواست خود را به ایمیل info@jobvision.ir ارسال نمایید تا درخواست شما توسط جاب ویژن بررسی شده و پس از تایید نهایی، حساب کاربری شما بطور کامل از سایت حذف گردد."


در issue شماره #23 درخواست تصحیح شده را ثبت کردم.

**Comment by amirshnll** [comment]
@Matin-B <br />

مرسی متین جان بابت توضیحت

**Comment by amirshnll** [comment]
@IVIosi <br />
مصطفی جان از اینکه مشارکت می کنی ممنونم سرویس های بیشتری رو اگر دوست داشتی معرفی کن
