### ISSUE TITLE
رایچت

### ISSUE THREAD

**Issue by Hameds** [amirshnll/rtbf.ir#21]
"name" : "رایچت"
"website": "https://raychat.io/"
"deleteurl": ""
"info": "غیر قابل حذف"

**Comment by Matin-B** [comment]
درود

من با پشتیبانیشون صحبت کردم و برای حذف حساب کاربری این دقیقا متنی بود که برای من ارسال کردند:
"برای حذف وب سایت لطفا با ایمیل اصلی سایتتون (info) یک ایمیل به support@raychat.io ارسال کنید و درخواستتون رو مطرح کنید تا براتون حذف بشه."


خودم درخواست ثبت کردم و همچنان منتظرم اما با این توضیحات فکر کنم فقط باید این توضیحات در بخش info نوشته  و با برچسب "سخت" منتشر بشه.

**Comment by Hameds** [comment]
@Matin-B ممنونم بابت پیگیری. من یک ایمیل برای درخواست حذف حساب کاربری فرستادم و درخواست کردم اطلاعات به صورت کامل (نه حذف منطقی) حذف بشن. تجربه رو اینجا خواهم نوشت
