### ISSUE TITLE
new website/service

### ISSUE THREAD

**Issue by alr86** [amirshnll/rtbf.ir#212]
"name" : "Shad"
"website": "https://shad.ir/"
"deleteurl": "ندارد"
"info": ""

**Comment by amirshnll** [comment]
@alr86 

سلام مرسی از مشارکتتان بعد از بررسی به دایرکتوری اضافه می شود

**Comment by amirshnll** [comment]
@Matin-B

**Comment by Matin-B** [comment]
> "name" : "Shad" "website": "https://shad.ir/" "deleteurl": "ندارد" "info": ""

درود
با تشکر از مشارکت شما.
در حال بررسی می باشد و بزودی اضافه خواهد شد.
