### ISSUE TITLE
دریافت توضیحات از سرویس های موجود

### ISSUE THREAD

**Issue by amirshnll** [amirshnll/rtbf.ir#44]
سرویس های موجود در لیست از سرویس مطلع شوند و اگر اشتباهی در ثبت هست اصلاح کنیم؛ گزارش گفتگو در این بخش اضافه بشه

<br />

- [x] #48
- [x] اسنپ
- [x] پونیشا
- [x] تپسی
- [x] #82
- [x] زوپ
- [x] سازیتو
- [x] جشنواره وب و موبایل ایران
- [x] زرین پال
- [x] #51
- [x] جابینجا
- [x] ابرآروان
- [x] فیلیمو
- [x] #53
- [x] اُکالا
- [x] نوبیتکس
- [x] روبیکا
- [x] PersianGig - پرشین‌گیگ
- [x] دکورشاپ
- [x] کافیته
- [x] افرانت
- [x] دیجی پی
- [x] همراه کارت
- [x] میهن وبهاست
- [x] نوبتی
- [x] #49
- [x] کوئرا
- [x] مفید آنلاین
- [x] کارزار
- [x] میل چی
- [x] یکتا نت
- [x] اپلیکیشن آپ
- [x] راست چین
- [x] ژاکت
- [x] رسمیو
- [x] سازمان بین المللی دانشجویان
- [x] #52
- [x] پارس پک
- [x] او‌ام‌پی فینکس
- [x] #50
- [x] سی‌نما
- [x] رند دات‌‌آی‌آر
- [x] دیجیاتو
- [x] تلوبیون
- [x] سی‌وی‌بیلدر
- [x] کاربوم
- [x] فرادرس
- [x] فرانش
- [x] تسکولو
- [x] آلاء
- [x] اُتیچر
- [x] ایوند
- [x] آیدی پی
- [x] ایران سرور
- [x] طاقچه

**Comment by Matin-B** [comment]
من سعی می‌کنم در روز های آینده با پشتیبانی سرویس های ثبت شده صحبت کنم که هم اطلاع داشته باشند و هم از درستی اطلاعات ثبت شده مطمئن باشیم.
همچنین بنظرم در کنار نام وبسایت لوگو همان سرویس هم قرار بدیم.

**Comment by amirshnll** [comment]
> من سعی می‌کنم در روز های آینده با پشتیبانی سرویس های ثبت شده صحبت کنم که هم اطلاع داشته باشند و هم از درستی اطلاعات ثبت شده مطمئن باشیم.
> همچنین بنظرم در کنار نام وبسایت لوگو همان سرویس هم قرار بدیم.

چک لیست سرویس هایی که باید بررسی بشن بالا هست هر کدوم تموم شد نتیجه رو لطفا اعلام کن و تیک بزن متشکرم

**Comment by amirshnll** [comment]
@Matin-B 
<br />
ساختار برچسب ها کمی تغییر کرده برای سرویس های جدید لطفا از ساختار جدید استفاده کن متشکرم

**Comment by Matin-B** [comment]
@amirshnll 
حتما. چند روزی هست که دسترسی به سیستم ندارم. از چند روز آینده کار را ادامه میدم.
(حداقل برای ۵۰ سرویس ثبت شده ایمیل ارسال کردم اما همچنان دریافت نکردم)

**Comment by amirshnll** [comment]
https://twitter.com/glist_ir/status/1414233189263060994?s=20

<br />
بررسی شود

**Comment by amirshnll** [comment]
برچسب ها تبدیل به این موارد شده <br />

- impossible-label
- hard-label
- medium-label
- easy-label

> @amirshnll
> حتما. چند روزی هست که دسترسی به سیستم ندارم. از چند روز آینده کار را ادامه میدم.
> (حداقل برای ۵۰ سرویس ثبت شده ایمیل ارسال کردم اما همچنان دریافت نکردم)

**Comment by amirshnll** [comment]
از این لینک سرویس های مختلف رو میشه پیدا کرد: <br />
http://dir.iran.ir/

**Comment by amirshnll** [comment]
@Matin-B <br />
متین جان اگر لینکی داخل توضیحات قرار میگیره حتما توی صفحه ی جدید باز بشه

**Comment by amirshnll** [comment]
@Matin-B متین جان سرویس هارو اگر پیگیری کردی ادیت ها فراموش نشه متشکرم

**Comment by Matin-B** [comment]
> @Matin-B متین جان سرویس هارو اگر پیگیری کردی ادیت ها فراموش نشه متشکرم

حتما. اگر ادیتی انجام نشده یعنی هنوز سرویس ها پاسخی ندادند. با این حال سعی می‌کنم در این هفته دوباره پیگیری کنم.

**Comment by amirshnll** [comment]
@Matin-B <br />

متین جان بابت پیگیری های خوبت واقعا متشکرم خیلی منظم انجام میشه اگر سرویس های جدیدی به ذهنت میرسه هم میتونی اضافه کنی فقط نکته اینه اول سرویس های مهم تر رو اضافه کنیم چون اگر سرویس های بزرگ همراهی کنن ارزش بیشتری ایجاد میشه به دلیل تعداد یوزر

**Comment by Matin-B** [comment]
> @Matin-B
> 
> متین جان بابت پیگیری های خوبت واقعا متشکرم خیلی منظم انجام میشه اگر سرویس های جدیدی به ذهنت میرسه هم میتونی اضافه کنی فقط نکته اینه اول سرویس های مهم تر رو اضافه کنیم چون اگر سرویس های بزرگ همراهی کنن ارزش بیشتری ایجاد میشه به دلیل تعداد یوزر

خواهش می‌کنم. خوشحالم که در این پروژه مشارکت می‌کنم. حتما سعی می‌کنم سرویس های مهم و شناخته شده را اولویت قرار بدم و باهاشون ارتباط برقرار بکنم. دلیل اینکه خیلی زیاد فعال نیستم اینه که من Full-time مشغول به کار هستم و معمولا شب ها میتونم با سرویس ها در ارتباط باشم و چون خارج از ساعات اداری هست ممکنه بیشتر زمان ببره.

**Comment by amirshnll** [comment]
https://twitter.com/alieverydaylife/status/1430517264802107396?s=20

<br />

@Matin-B 

<br />

متین جان این مورد رو هم بررسی کن و به سرویس اضافه کن

**Comment by Matin-B** [comment]
> https://twitter.com/alieverydaylife/status/1430517264802107396?s=20
> 
> 
> @Matin-B
> 
> 
> متین جان این مورد رو هم بررسی کن و به سرویس اضافه کن

بعد از بررسی اضافه شد.

**Comment by amirshnll** [comment]
@Matin-B <br />

اگر بیش از 15 روز از سرویسی جواب نگرفتی و داخل قوانین اون سایت نبود بند حذف حساب کاربری یا اینکه عضو شدی و بررسی کردی و چیزی نداشت داخل پنلشون برچسب غیرممکن بزن

**Comment by Matin-B** [comment]
> @Matin-B
> 
> اگر بیش از 15 روز از سرویسی جواب نگرفتی و داخل قوانین اون سایت نبود بند حذف حساب کاربری یا اینکه عضو شدی و بررسی کردی و چیزی نداشت داخل پنلشون برچسب غیرممکن بزن

Ok
از فردا دوباره لیست را بررسی و اضافه می‌کنم.

**Comment by amirshnll** [comment]
@Matin-B <br />

اگر توضیحات خاصی بهت از سرویس های باقی مونده نرسید این  بخش رو هم ببندش اگر میخواستن جواب بدن تا حالا داده بودن یا اگر دوست داری به باقیمونده ی لیست ایمیل مجدد بده و چندروز مجدد صبر کن
