### ISSUE TITLE
طراحی گرافیکی

### ISSUE THREAD

**Issue by amirshnll** [amirshnll/rtbf.ir#45]
- [x] لوگو
- [x] طرح های سوشال مدیا برای معرفی
- [x] شعار و طرح
- [x] معرفی سرویس برای شبکه های اجتماعی
- [x] طراحی المان های صفحات داخلی
- [x] طراحی فوتر
- [x] اصطلاحات UI 
- [x] پیشنهادات توسعه وبسایت
- [x] Guide Color
- [x] طراحی بنر وبسایت
- [x] بج آنلاین
- [x] اینفوگرافیک

**Comment by irSodeh** [comment]
**کارهای ذیل انجام و ایمیل شد**
لوگوی نهایی وبسایت
ایکون وبسایت
طراحی آیکون های پیشنهادی و مناسب برای استیکر
طراحی چهار طرح استیکر


**درخواست ارسال اطلاعات**
https://www.copyscape.com/banners.php  (همه سایز ها باید بزنم؟)
اطلاعات مورد نیاز برای پست های اینستاگرام


**پیشنهادات برای بهبود سایت**
اضافه کردن لوگو سایت ها
طراحی بنر سایت با طرح لوگو
افزودن امکان جستجو سرویس ها و سایت ها
افزودن امکان دسته بندی به سایت بر اساس (موضوعی/ ایرانی و خارجی / سختی و....)
اصلاح جمله فوتر:
2021© | این سرویس به صورت متن‌باز و با لایسنس Apache-2.0 License منتشر شده است
اصلاح فوتر 
درآوردن پالت رنگ برای سایت
اضافه کردن یه طرح جذاب برای صفحه حمایت مالی

**Comment by irSodeh** [comment]
سه طرح برای پست سوشال مدیا + قالب کپشن ارسال شد
بنر معرفی سرویس برای وبسایت طراحی شد
راهنمای رنگ وبسایت اعلام شد
فوتر طراحی و کد رنگ ها اعلام شد
سه تصویرسازی برای بخش های حمایت مالی، پرسش های متداول، بلاگ و درباره ما انجام شد
اصلاحات رابط کاربری اعلام شد
مجددا لیست ایشوها بروز شد

**Comment by irSodeh** [comment]
فایل های طراحی ایمیل شد
