### ISSUE TITLE
fandogh.cloud

### ISSUE THREAD

**Issue by s-soroosh** [amirshnll/rtbf.ir#70]
سلام وقت بخیر 

من نسبت به ثبت سایت/سرویسم اعتراضم دارم برای نداشتن قابلیت حذف حساب کاربری دلیل مجموعه ی ما به شرح زیر می باشد:

پلتفرم ابری فندق این امکان را دارد ولی در وب سایت **غیر ممکن** درج شده است.

**Comment by amirshnll** [comment]
سلام سروش جان مرسی که اطلاع دادی اگر جزئیات رو اعلام کنی حتما اصلاح میشه

**Comment by s-soroosh** [comment]
> سلام سروش جان مرسی که اطلاع دادی اگر جزئیات رو اعلام کنی حتما اصلاح میشه

سلام امیر جان

به نظر توضیحات به درستی ذکر شده‌اند فقط در نهایت label هنوز تکستش غیر ممکن بوده و عوض نشده.

**Comment by Matin-B** [comment]
> سلام وقت بخیر
> 
> من نسبت به ثبت سایت/سرویسم اعتراضم دارم برای نداشتن قابلیت حذف حساب کاربری دلیل مجموعه ی ما به شرح زیر می باشد:
> 
> پلتفرم ابری فندق این امکان را دارد ولی در وب سایت **غیر ممکن** درج شده است.

درود
وقت بخیر

همکاران شما با من در ارتباط بودند. در توضیحات شما بخشی تحت عنوان "مواردی که حذف نمی‌شوند" هست که از نظر شخصی بنده این به معنای حذف اکانت نیست. از نظر من حذف اکانت به معنای حذف کامل تمامی اطلاعات مربوط به یک کاربر هست به همین خاطر فکر کنم بهتر هست @amirshnll  نظرش را بیان کنه و اگر صلاح میدونه لیبل را ویرایش کنه.

**Comment by s-soroosh** [comment]
> > سلام وقت بخیر
> > من نسبت به ثبت سایت/سرویسم اعتراضم دارم برای نداشتن قابلیت حذف حساب کاربری دلیل مجموعه ی ما به شرح زیر می باشد:
> > پلتفرم ابری فندق این امکان را دارد ولی در وب سایت **غیر ممکن** درج شده است.
> 
> درود
> وقت بخیر
> 
> همکاران شما با من در ارتباط بودند. در توضیحات شما بخشی تحت عنوان "مواردی که حذف نمی‌شوند" هست که از نظر شخصی بنده این به معنای حذف اکانت نیست. از نظر من حذف اکانت به معنای حذف کامل تمامی اطلاعات مربوط به یک کاربر هست به همین خاطر فکر کنم بهتر هست @amirshnll نظرش را بیان کنه و اگر صلاح میدونه لیبل را ویرایش کنه.

سلام

از اونجا که این موارد به صورت ناشناس ذخیره میشن (کاری که همه جای دنیا اتفاق میفته) امکان مرتبط ساختن مجدد اونا به کاربر وجود نداره.

**Comment by amirshnll** [comment]
<div dir="rtl">

@Matin-B 

<br />
متین جان از لحاظ قانونی یک سری از اطلاعات متاسفانه قابل حذف نیست و دلیل اون بحث های مالی و ... میتونه باشه ولی به صورت soft delete هم قابل قبول هست

<br />

سرویس های مختلف خارجی هم این مورد حذف رو تا حدی مشکل دارن ولی تا حد ممکن باید اگر مشکل قانونی شرکت ها نخورن باید حذف اطلاعات داشته باشن مرسی از پیگیری های کامل و خوبت واقعا ارزشمند هست

<br />

@s-soroosh 

<br />

من به عنوان "سخت" سرویس فندق رو برچسب زدم امیدوارم و خیلی خوشحالم که صفحه ای تحت این عنوان اضافه کردین و توضیحات شفافی در مورد این موضوع دادین این موضوع قابل تحسین هست

</div>

**Comment by s-soroosh** [comment]
ممنون از شما دوستان که به این تاپیک اهمیت میدید و از شرکت‌ها هم این مورد رو طلب میکنید.
