### ISSUE TITLE
new website/service

### ISSUE THREAD

**Issue by BlackIQ** [amirshnll/rtbf.ir#72]
"name" : "jobnic"
"website": "https://jobnic.net"
"deleteurl": "https://jobnic.net/user/?tab=settings"
"info": "سایت جاب نیک محلی برای پیدا کردن پروژه های کوچک و معمولا دانشگاهی میباشد"

**Comment by amirshnll** [comment]
@BlackIQ <br />

بعد از بررسی به لیست اضافه شد موفق باشید

**Comment by BlackIQ** [comment]
همچنین. ممنون.
