### ISSUE TITLE
new website/service

### ISSUE THREAD

**Issue by peyman4** [amirshnll/rtbf.ir#73]
"name" : ""صرافی ارز دیجیتال ایران بایننس
"website": ""https://ibnns.net/
"deleteurl": ""
"info": ""صرافی ارز دیجیتال ایران بایننس یکی از صرافی های معتبر و مشهور در کشور ما هست که به نسخه ایرانی صرافی بزرگ بایننس  مشهور است و با پشتیبانی از 600 ارز دیجیتال معتبر برای خرید و فروش، یکی از بهترین گزینه ها برای خرید و فروش ارزهای دیجیتال به شمار می آید که در طی فعالیت چند ساله خود توانسته کارنامه درخشانی از خود به جا بگذارد. صرافی ارز دیجیتال ایران بایننس برای اولین بار در سال 1395 با هدف پر کردن خلاء پلتفرم ایرانی برای معاملات ارز دیجیتال شروع به کار کرد. اولین اصل در این صرافی آسان سازی معاملات ارز دیجیتال برای تمامی اقشار جامعه بود که خوشبختانه تا به امروز طبق گفته کابران سایت آسانترن و سریع ترین سیستم معاملاتی را در بین سایت های ایرانی داشته است.

از آنجایی که امروزه خرید و فروش ارزهای دیجیتال برای کاربران ایرانی از طریق صرافی های خارجی ارزهای دیجیتال با مشکلات فراوانی همراه هست، بخاطر همین ایران بایننس این امکان را فراهم آورده که کاربران ایرانی بدون دغدغه و هیچ مشکلی بتوانند بصورت 24 ساعته و در طی هفت روز هفت از خدمات این صرافی استفاده کنند و در سریع ترین زمان به خرید و فروش دارایی های دیجیتال خود بپردازند.

**Comment by amirshnll** [comment]
#stopspam
