### ISSUE TITLE
new website/service

### ISSUE THREAD

**Issue by Gnkalk** [amirshnll/rtbf.ir#89]
"name" : "چاپار میل"
"website": "chmail.ir"
"deleteurl": ""
"info": "غیر ممکن"

**Comment by Matin-B** [comment]
درود
مرسی بابت مشارکت
ایمیل برای پشتیبانی ارسال شد. پس از بررسی اضافه خواهد شد.

**Comment by Matin-B** [comment]
اضافه شد.


سپاس بابت مشارکت
