### ISSUE TITLE
مشکل نمایش لوگو در Dark Mode

### ISSUE THREAD

**Issue by Matin-B** [amirshnll/rtbf.ir#90]
به دلیل اینکه متن تصویر موجود در README.md مشکلی هست در Dark Mode متن درست نمایش داده نمیشه
![dark_mode](https://user-images.githubusercontent.com/50226354/140292097-d80d4a35-e698-48a9-8c8c-a660e6f5c3bf.png)
<hr />

پیشنهاد من قرار دادن Border سفید به متن های درون تصویر هست که هم داخل Light Mode و هم Dark Mode به درستی نمایش داده بشه.
نمونه تصویر قرار داده شده در [ریپازیتوری Next.js](https://github.com/vercel/next.js):
![next_dark](https://user-images.githubusercontent.com/50226354/140293267-dbb6810c-cd09-4c3a-98fa-58ccd8d593c7.png)

@irSodeh @amirshnll

**Comment by amirshnll** [comment]
@Matin-B مرسی از اطلاعت <br />
تغییرات رو داخل ریپو ببین اگر فیکس شد این بخشو کلوز کن
