### ISSUE TITLE
niciu.ir

### ISSUE THREAD

**Issue by niciuir** [amirshnll/rtbf.ir#91]
"name" : "امور آموزش و تجهیز نیروی انسانی مجتمع مس سرچشمه"
"website": "niciu.ir"
"deleteurl": ""
"info": ""

**Comment by Matin-B** [comment]
درود
پس از بررسی اضافه خواهد شد.

**Comment by Matin-B** [comment]
@niciuir 
اینطور که پیداست این issue بیشتر اهداف تبلیغاتی دارد تا مشارکت و مناسب ثبت در این پروژه نیست.
