### ISSUE TITLE
gama.ir

### ISSUE THREAD

**Issue by F4R4N** [amirshnll/rtbf.ir#92]
"name" : "گاما"
"website": "gama.ir"
"deleteurl": "#"
"info": "امکان حذف وجود ندارد"

**Comment by Matin-B** [comment]
درود
پس از بررسی اضافه خواهد شد.

**Comment by F4R4N** [comment]
![Screenshot (84)](https://user-images.githubusercontent.com/51335574/145601120-5cc0a8c9-c939-4776-84d7-650217b5a276.png)
پاسخشون به چگونگی حذف حساب کارب

**Comment by amirshnll** [comment]
@F4R4N 

مرسی از پیگیریت
