### ISSUE TITLE
گاما

### ISSUE THREAD

**Issue by F4R4N** [amirshnll/rtbf.ir#96]
مثل اینکه برای حذف حساب کاربری در وبسایت گاما باید:

1. به آدرس https://gama.ir/ticket/newticket رفت
2. موضوع را سایر موارد انتخاب کنید
3. عنوان را "حذف حساب کاربری بیان کنید"
4. در توضیحات بگید که میخواید به طور کامل حساب کاربریتون رو حذف کنید(و احتمالا اونا اصرار میکنن که توضیح بدید چرا)
5. معمولا طی 24 ساعت جواب میدن و تایید نهایی میخوان و با تایید کاربر حساب رو حذف میکنن

**Comment by amirshnll** [comment]
@Matin-B 

<br />
 
برچسب سخت داشته باشه
