### ISSUE TITLE
پونیشا

### ISSUE THREAD

**Issue by ribrea** [amirshnll/rtbf.ir#97]
من نسبت به ثبت سایت/سرویسم اعتراضم دارم برای نداشتن قابلیت حذف حساب کاربری دلیل مجموعه ی پونیشا به شرح زیر می باشد:

تو پونیشا با ایمیل زدن به پشتیبانی میتونید حساب خودتونو حذف کنید :D

با احترام
AE

**Comment by Matin-B** [comment]
درود 
در پونیشا صفحه ای تحت عنوان "[چطور حساب کاربری را حذف کنم؟](https://ponisha.ir/help/article/%DA%86%D8%B7%D9%88%D8%B1-%D8%AD%D8%B3%D8%A7%D8%A8-%DA%A9%D8%A7%D8%B1%D8%A8%D8%B1%DB%8C-%D8%B1%D8%A7-%D8%AD%D8%B0%D9%81-%DA%A9%D9%86%D9%85%D8%9F/)" وجود دارد اما در جواب این سوال تنها به مسدود کردن حساب کاربری اشاره شده است و دلیل اصلی قرار نگرفتن پونیشا به عنوان سرویسی با قابلیت حذف حساب کاربری بند زیر می‌باشد:

> پس از مسدود شدن هیچکدام از اطلاعات شما از سایت حذف نمی‌شود فقط به اطلاعات بی‌نام تغییر خواهند کرد و تصویر و نام‌کاربری شما دیگر در سایت نمایش داده نخواهد شد.




@amirshnll نظر شما چی هست؟

**Comment by amirshnll** [comment]
@Matin-B 

<br />

با توجه به شرایط قانونی هیچکدوم از وبسایت هایی که میگن حذف میکنن واقعا حذف نمیکنن اول اینکه از لحاظ مالی حداقل باید 5 سال اخیر رو داشته باشن ولی در حالت کلی همین که اطلاعات غیرقابل دیدن روی وب بشه روی موتورجستجو ها نمونه و جایی قابل دسترسی نباشه کافیه
<br />
از بابت سایت فعلی توضیحات رو بنویس داخل کارت پونیشا اما برچسبش از حالت غیرممکن تغییر نکنه

**Comment by Matin-B** [comment]
اطلاعات تکمیلی در قسمت توضیحات سرویس اضافه شد و به همین دلیل این issue را میبندم. اگر همچنان موردی بود لطفا در همین issue مطرح کنید.
